# Generated by Django 6.1.1 on 2026-09-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('rows', models.PositiveIntegerField()),
                ('tables_per_row', models.PositiveIntegerField()),
                ('seats_per_table', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
