# Generated by Django 6.1.1 on 2026-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
