# Generated by Django 6.1.1 on 2026-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='branches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
